# Generated by Django 5.0.4 on 2026-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='season_end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12. Leave both season fields blank for a year-round product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='season_start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12. Leave both season fields blank for a year-round product.', null=True),
        ),
    ]