# Generated by Django 5.0.4 on 2026-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_seasonal_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_surplus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Alert this producer when stock falls to or below this level. Leave blank to disable.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_expires_at',
            field=models.DateTimeField(blank=True, help_text='When this surplus deal stops being offered. Required if is_surplus is set.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='surplus_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
