# Generated by Django 5.0.4 on 2026-07-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_is_surplus_product_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Delivery notes covering the whole order, e.g. "deliver to kitchen entrance, ask for the kitchen manager" — useful for bulk/institutional orders.'),
        ),
    ]
